### ISSUE TITLE
Cats version used in examples is outdated

### ISSUE THREAD

**Issue by mttkay** [scala-exercises/exercises-cats#39]
The exercises are 3 major versions behind cats at the time I write this (they use 0.4.x where 0.7.x is the latest release.) Some exercise code does not compile anymore, e.g. due to the removal of the `cats.std` package. I tried updating cats to 0.7 and fixed all the compilation errors (they were mostly due to implicit conversions having moved to `cats.implicits._`) but ran into a chain of binary incompatibilities with the dependencies when executing the tests. I gave up at this point:

```
  libraryDependencies ++= Seq(
    "org.typelevel" %% "cats-core" % "0.7.0",
    "com.chuusai" %% "shapeless" % "2.3.2",
    "org.scalatest" %% "scalatest" % "2.2.6",
    "org.scala-exercises" %% "exercise-compiler" % version.value,
    "org.scala-exercises" %% "definitions" % version.value,
    "org.scalacheck" %% "scalacheck" % "1.13.2",
    "com.github.alexarchambault" %% "scalacheck-shapeless_1.13" % "1.1.1",
    compilerPlugin("org.spire-math" %% "kind-projector" % "0.7.1")
  )
```
I bumped shapeless (minor), scalatest (patch), scalacheck (minor) and scalacheck-shapeless (minor)

Something is still wrong though, as the test runner cannot find a class it's expecting:

```
An exception or error caused a run to abort: Implementing class 
java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at catslib.MonoidSpec.<init>(MonoidSpec.scala:9)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:2644)
	at org.scalatest.tools.Runner$$anonfun$37.apply(Runner.scala:2461)
	at org.scalatest.tools.Runner$$anonfun$37.apply(Runner.scala:2460)
	at scala.collection.immutable.List.map(List.scala:273)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2460)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
It appears there is some binary incompatibility between the dependencies somewhere. I also tried replacing ScalaTest with the latest major release 3, but that failed with other obscure errors.

Could this be related to the exercise-compiler? What does it do and where can one look at it? Any advice or someone else looking into this?

**Comment by mttkay** [comment]
Okay, so this is why: http://stackoverflow.com/questions/35312410/java-lang-incompatibleclasschangeerror-implementing-class-with-scalacheck-and-s

I reverted the scalacheck bump, but now I'm back to where I started, a binary incompatibility between cats 0.7 and scalacheck:

```
NoSuchMethodError was thrown during property evaluation.
  Message: cats.NotNull$.notNull()Lcats/NotNull;
  Occurred when passed generated values (
    arg0 = 15 :: 12345 :: HNil
  )
```
Which occurs in every test. :-|

**Comment by raulraja** [comment]
This is probably because the runtime definitions dependencies pull in an old version of cats and they conflict in the same classloader. Remote evaluation again's the scala exercises evaluator would work because the remote evaluator uses it's own classloader to keep invocations and dependencies isolated. I wonder if we can embed the evaluator an pipe the tests through it which will also serve as integration tests since the evaluator is where code will ultimately run.
https://github.com/scala-exercises/evaluator

**Comment by mttkay** [comment]
\o/

**Comment by juanpedromoreno** [comment]
Hi @mttkay, the new build is being deployed at this moment. It should be ready soon (using cats 0.7.2). BTW, I created https://github.com/scala-exercises/exercises-cats/issues/46 to finish the complete update.

**Comment by mttkay** [comment]
Thanks, great job!
